### ISSUE TITLE
Ngk bisa running, pas klik hajar ngk terjadi apa2

### ISSUE THREAD

**Issue by yayatply** [lorosukmo/undian#1]
Ngk bisa running, pas klik hajar tdk terjadi apa2

- folder database udah di copykan di mysql/data

**Comment by kalingga** [comment]
- coba untuk databasenya di import melalui phpmyadmin/sejenisnya.
- kemudian mohon infokan konfigurasi di path `undian/core/config.php`
- coba anda akses [http://localhost/undian/data.php](http://localhost/undian/data.php), kalau muncul `{"total":"success"}` seharusnya tidak masalah.
