### ISSUE TITLE
tampilan blank dan ga jalan

### ISSUE THREAD

**Issue by nriefff** [lorosukmo/undian#2]
gan . boleh tolong bantu kenapa di localhost saya ga berjalan aplikasinya ? hanya blank dan diam saja pas di klik .
saya menggunakan xampp dan [PHP/7.2.3]
![Screenshot (752)](https://user-images.githubusercontent.com/56390263/66559308-5a4ed300-eb7f-11e9-94dd-309a0c09a09a.png)

**Comment by kalingga** [comment]
pastikan database *.sql sudah di import. dan pengaturan koneksi database  di core/config.php benar.
